In [1]:
import torch

In [19]:
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
tensor_2d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
diagonal_elements = torch.diagonal(tensor_2d).unsqueeze(1)
diagonal_elements

tensor([[1],
        [5],
        [9]])

In [28]:
temp = torch.cat([tensor_2d, diagonal_elements], dim = 1)
temp

tensor([[1, 2, 3, 1],
        [4, 5, 6, 5],
        [7, 8, 9, 9]])

In [14]:
bs = 3

In [17]:
hard_negative_columns = torch.arange(bs)
hard_negative_columns

tensor([0, 1, 2])

In [21]:
torch.cat([tensor_2d, tensor_2d[:, hard_negative_columns]], dim=1)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]])

In [22]:
tensor_2d[:, hard_negative_columns]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])