In [1]:
import os
import numpy as np

In [2]:
temp = [355099, 528417, 534704]

In [4]:
np.array(temp, dtype=int)

array([355099, 528417, 534704])

In [ ]:
temp = [355099, 528417, 534704]

In [7]:
temp2 = np.isin([295260, 154188, 459306, 441068, 469312, 355099, 528417, 534704], [355099, 528417, 534704])
temp2

array([False, False, False, False, False,  True,  True,  True])

In [10]:
np.cumsum(temp2, axis = 0)/np.arange(1, temp2.shape[0] + 1)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16666667, 0.28571429, 0.375     ])